apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTgwOTgxMjEwMzc5L2FuYWx5dGljcy1xdWV1ZQ==
  AWS_DYNAMODB_TABLE: YW5hbHl0aWNzLWRi
