apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpLaEJ1MGglN0NBRzlxZFBsY3hOZDRUaSU3Q0x4clRCJTNDQHRvZ2dsZW1hc3Rlci1kYi5jeDN3OHdhb3F4cmsudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYj9zc2xtb2RlPXJlcXVpcmU=
  MASTER_KEY: MzY0MzE3NDUwY2NhOWQ3MWFjMjYzNDY2NjU1NDBlZTFiNzc1OTMwMGMwNGZmYmNhNGQ5OWViMWViZTg2NTE1MQ==
