apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
type: Opaque
data:
  REDIS_URL: cmVkaXNzOi8vY2x1c3RlcmNmZy5ldmFsdWF0aW9uLWNhY2hlLjl4c2t6Yi51c2UxLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OQ==
  AWS_REGION: dXMtZWFzdC0x
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMTgwOTgxMjEwMzc5L2FuYWx5dGljcy1xdWV1ZQ==
  SERVICE_API_KEY: dG1fa2V5XzRiZDhmMWE3M2NiMjZkYzc3MDI1Nzk3ZjViNzZhMzI4MzgyNjRmNmZlNjkxYzViNTFlZjg5M2Q0Mzg1MzUyNDk=
