apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-secret
type: Opaque
data:
  POSTGRES_HOST: dG9nZ2xlbWFzdGVyLWRiLmN4M3c4d2FvcXhyay51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: S2hCdTBofEFHOXFkUGxjeE5kNFRpfEx4clRCPA==
