apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpLaEJ1MGglN0NBRzlxZFBsY3hOZDRUaSU3Q0x4clRCJTNDQHRvZ2dsZW1hc3Rlci1kYi5jeDN3OHdhb3F4cmsudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvdGFyZ2V0aW5nX2RiP3NzbG1vZGU9cmVxdWlyZQ==
