apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
