apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
type: Opaque
stringData:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: fake
  AWS_SECRET_ACCESS_KEY: fake
  AWS_SESSION_TOKEN: fake
  AWS_SQS_ENDPOINT_URL: http://elasticmq:9324
  AWS_DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
  AWS_SQS_URL: http://elasticmq:9324/000000000000/evaluation-queue
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
