apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/auth_db"
  MASTER_KEY: "admin-secreto-123"
