apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/flags_db"
